dist: trusty
cache:
    npm: false

language: node_js
node_js:
    - 'v14' # ends April 2021

env:
    - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:
    - openssl aes-256-cbc -K $encrypted_5abe573128c6_key -iv $encrypted_5abe573128c6_iv
      -in assets/server.key.enc -out assets/server.key -d
    - export SFDX_AUTOUPDATE_DISABLE=false
    - export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
    - export SFDX_DOMAIN_RETRY=300
    - export SFDX_DISABLE_APP_HUB=true
    - export SFDX_LOG_LEVEL=DEBUG
    - npm cache clean --force
    - npm install
    - mkdir sfdx
    - wget -qO- $URL | tar xJ -C sfdx --strip-components 1
    - './sfdx/install'
    - export PATH=./sfdx/$(pwd):$PATH
    - sfdx --version
    - sfdx plugins --core
    - sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
      --username $USERNAME --setdefaultdevhubusername -a HubOrg
script:
    - set -e
    - sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg -d 1 --wait 4
    - sfdx force:org:display -u ciorg
    - sfdx force:source:push -u ciorg
    - set +e
    - sfdx force:apex:test:run -u ciorg --codecoverage -r human -d ~/apex_tests --wait 10
    - npm run test:unit:coverage
    - cp ~/apex_tests/test-result-codecoverage.json .
    - bash <(curl -s https://codecov.io/bash)
    - rm -f test-result-codecoverage.json
    - node_modules/codecov/bin/codecov
    - sfdx force:org:delete -u ciorg -p
